### ISSUE TITLE
Error when lauching "demoDSen2.m"

### ISSUE THREAD

**Issue by jmifdal** [lanha/DSen2#12]
Hello, 

When I run the file "demoDSen2.m" I have the following error:
 "> In DSen2 (line 52)
Error using predict (line 84)
Invalid calling syntax for the "predict" command. Type "help
predict" for more information.

Error in DSen2 (line 53)
    pred = predict(net60, q_image/2000)*2000;"

I use matlab R2017a and I have all the necessary toolboxes, do you think the matlab version might be the source of the problem? Would it be possible that you please check the version you deposited in Github just to make sure that the problem does not come from somewhere else? 

Thank you in advance.
Best,

**Comment by lanha** [comment]
Hi,
other people have noticed problems with the version of Matlab. As with #8 I think it will be solved if you can install 2018a or newer.
Best

**Comment by jmifdal** [comment]
Hi,
Thank you for your quick answer.
Unfortunately I cannot install the version 2018 or a newer one and I need
to compare my method with a deep-learning based one. Do you have any
deep-learning based super-resolution code or do you know where I can find
one please?
Thank you in advance.
Best,


Le mar. 17 sept. 2019 à 16:23, Charis Lanaras <notifications@github.com> a
écrit :

**Comment by lanha** [comment]
You can use the python code instead of Matlab then.

**Comment by Dinghaiyin** [comment]
Hi，in your paper I see that the network must be evaluated at lower sacle because there is no 10m groundtruth?WHY? The original 10m bands cannot be the groundtruth?
