### ISSUE TITLE
DSen2 for Sentinel-2 Level-2A Data

### ISSUE THREAD

**Issue by philipse2000** [lanha/DSen2#16]
Hi Charis,

DSen2 is doing a great job. Thanks a lot.

Could you also provide a version of the code that allows for the processing of Sentinel-2 Level 2A Data? 

Currently I run into problems because the sen2cor plugin (SNAP) does not accept the data after they have been processed with DSen2 and vice versa DSen2 does not accept the data which have been processed with sen2cor. But eventually, I need data that have been atmospherically corrected with sen2cor and afterwards sharpened with DSen2.

If you could work on this, I would be very happy.

Best regards!

**Comment by lanha** [comment]
Hello

Retraining DSen2 form scratch for Level 2A would be quite a big effort. Do you have any indication as to why sen2cor does not accept the data? It must have something to do with the metadata written into the file. If you can inject this information into the file sen2cor will probably work.

Best regards,
Charis

**Comment by philipse2000** [comment]
Hi Charis,
I think that sen2cor expects a dataset that is composed of bands with different spatial resolutions (10, 20 and 60 m). But after running DSen2 all bands have 10 m resolution. 
When I first run sen2cor and afterwards try to process the L2A data with DSen2 it is also not working. I assume this is because sen2cor changes the structure of the folders in which the image bands are stored. 

What would be your recommendation to solve this problem?

Best regards
Philip

**Comment by lanha** [comment]
Hello Philip

Then as it stands, it would make more sense to re-train DSen2 with Level 2A images. This is a quite big task for which I don't have the full capacity to perform right now. I could add it to my backlog, but the biggest issue I see is getting all the required data. May I ask, for what type of application you need this data?

Best,
Charis

**Comment by philipse2000** [comment]
Hi Charis,
It might not be an easy task to retrain DSen2 with Level 2A images as there is no standard for converting a L1C image into an L2A image. There are many different ways to process the Data. E.g. for the atmospheric correction of the L1C one could use several algorithms with diferent settings and it could be done with or without using a terrain model. I theory all methods should correct for athmospheric effects but in reality the results can be quite different. So you would have to decide which L2A images to use...

What happens if I do not use the pre-trained DSen2 model but do the training for each image myself? If I used an L2A image, which could be done by replacing the L1C bands with L2A bands in the L1C folder, to train the model, would that make sense? 

Cheers, 
Philip

**Comment by lanha** [comment]
Hello Philip

UP42 have created a fork that handles level 2A images. Might be worth checking that out: https://github.com/up42/DSen2

Regards,
Charis
