### ISSUE TITLE
Purpose of get_test_patches60

### ISSUE THREAD

**Issue by mugheesahmad** [lanha/DSen2#18]
hey, I am trying to understand your code but stuck on function called get_test_patches60. I am unable to understand the purpose of this function. Can you please guide me on why you used this function. 

Thanks alot.

**Comment by lanha** [comment]
Hello!

The purpose of the function `get_test_patches` is to sequentially, extract overlaping patches, such that they can recompose the original image after inference (for 10 and 20 m resolution bands).

The purpose of `get_test_patches60` as opposed to `get_test_patches60` is to extract all (10, 20, 60) resolution bands. Given that they relate to each other there are further constraints on the size the patches can take (and subsequently border replictation etc). Theoretically, only `get_test_patches60` would be enough for the purpose of this demo.

Best,
Charis

**Comment by mugheesahmad** [comment]
Thanks alot for the detailed response Chris. 

Regards,
