### ISSUE TITLE
VDSen2 Weights

### ISSUE THREAD

**Issue by JohMast** [lanha/DSen2#19]
Hi Charis,

Thank you for DSen2! I have just started playing with it and is working very well.

I would also like to test the VDSen2 model, but the download links do not appear to be working anymore. Is there any chance that you could refresh or update the links?

Thanks a lot!
Johannes

**Comment by lanha** [comment]
Hello Johannes

I have made the weights available here: https://www.transfernow.net/oCuqV4032020

Best, Charis

**Comment by JohMast** [comment]
Hi Charis,

Cool, thank you very much!

Best wishes,
Johannes

**Comment by mugheesahmad** [comment]
> Hello Johannes
> 
> I have made the weights available here: https://www.transfernow.net/oCuqV4032020
> 
> Best, Charis

Dear @lanha,
The transfernow link is expired. 

Regards.
Mughees
