### ISSUE TITLE
Is there a scope to further improve the model?

### ISSUE THREAD

**Issue by purijs** [lanha/DSen2#31]
Hi

I've tested the pre-trained model on quite a few regions and has been performing really well, however, I have few questions here

1. What kind of improvements can we expect by increasing training size for a specific area?
2. Can your training code be used push 10m further to 5m? Using the same approach by downscaling 10m to 20m?
3. In what scenarios is this model not good for or may not give expected results?

Thanks

**Comment by lanha** [comment]
Hello

unfortunately, there are no updates planned in the current timeframe. These are some nice research questions that might be worth exploring. If you have the capacity you can go ahead and implement them.

Thanks
