### ISSUE TITLE
Sir, I have a simple question :)

### ISSUE THREAD

**Issue by landkwon94** [lanha/DSen2#36]
Nice to meet you, I am a master course student from South Korea, and my major is Landscape Architecture. These days, I am trying to use your code and paper to make super resolution Sentinel-2 imagery. 

My question is that, if my imagery has :
Super resolution (about 5m?) R,G,B band and
NIR is just 10 m,

Then, could your code work well with the upper configuration?
Because original Sentinel-2 has 10m RGB and NIR. And other bands are low resolution.
But I have only RGB high resolution band and NIR is not that high resolution compared to RGB.

Many thanks for your nice work!
I will wait for your reply :)

**Comment by lanha** [comment]
Hi
Yes, I think it would work in principle, but you would need to slightly change the input and outputs of the network and then retrain it on your data.
