### ISSUE TITLE
Training the models

### ISSUE THREAD

**Issue by EmanuelCastanho** [lanha/DSen2#38]
Hi,

How should model training be done for a particular region? Should I only use cloudless or minimal cloud images?

Can sentinel 2 level 2A datasets be used in place of level 1C datasets without changing the code?

Thanks in advance for providing DSen2 source code.

**Comment by lanha** [comment]
Hi,

I recommend you use images with minimal/few clouds.

Yes, I believe you wouldn't need to change the code to train the network with level 2A datasets.

**Comment by EmanuelCastanho** [comment]
Thank you!
