### ISSUE TITLE
Data Load

### ISSUE THREAD

**Issue by wukongtea** [lanha/DSen2#7]
I have plenty of Sentinel-2 data need to be loaded , meanwhile,  I want to read the whole image of all bands Sentinel-2 data into Keras in a batch file directly. Can you provide the related code or give some suggestions?
Thank you  for your attention.

**Comment by lanha** [comment]
Sorry, I don't understand exactly what your problem is.

**Comment by wukongtea** [comment]
As we know Sentinel-2 imagery has almost 12 bands with different resolution.I have a large number of Sentinel-2 imagery need to be classified.Firstly, I want translate all bands of Sentinel-2 data to the 10m resolution by using the DSen2 . Then, I want to save those high-resolution images as GeoTIFF format so that  i can process them and get a better classification accuracy than the origin data.
How can I save the result  of DSen2 as the GeoTIFF format with batch processing operation?
Thank you very much.

**Comment by lanha** [comment]
Ok. You can either write a bash script that would specify the input and output files, or a python script doing more or less the same.

**Comment by wukongtea** [comment]
Thank you very much.
