### ISSUE TITLE
Sharpening selected bands

### ISSUE THREAD

**Issue by kegro** [lanha/DSen2#9]
Thanks for making this public and the nice documentation! It works very smoothly. This is a request, rather than an actual issue.  I'm processing lots of S2 data - thousands of tiles. I'd really like to integrate this into the processing stream however its taking too long to process given the computing power I have available - I've tested on both cpu and a decent gpu. It would be really nice, and highly useful, if you could have the option to sharpen just a single 20m band, or a more refined selection of bands. Would it be possible to add this functionality?

**Comment by lanha** [comment]
Unfortunately, the current version of the network (and the weights) are configured to output all the sharpened bands of Sentinel-2. What you are describing could be done with retraining the network to output specific bands, but the gain in speed won't be so significant.
